### PR TITLE
feat: django-storages support, fixes #13

### LINKED ISSUE #13: Make sure it works with django-storages...
...especially with AWS S3

### PR DESCRIPTION
**Pull request by escaped**
Add support for `django-storages`. This PR is based on #19 and #14 .

fixes #13

### CODE REVIEW

**Comment by lifenautjoe** [comment]
Looks good!

**Comment by escaped** [comment]
Yeah, it does. What I like to add before I merge this PR is to add a test. Unfortunately, I haven't found the time to write one yet.

**Comment by escaped** [comment]
@lifenautjoe @bashu I just finished the work on this PR. Would be great if you guys could check it out and tell if you find any issues. :pray: 
I added a test (using a FakeRemoteStorage) and did some refactoring as well, so simplify the codebase. There is still quite some stuff which could be improved, but that is definitely out of scope :roll_eyes: Anyway, thanks again for you efforts.

**Comment by lifenautjoe** [comment]
Hi Alexander! I've been following up the PR :-). Will run my integration tests with this branch and will come back to you.

Thanks for the great work!

**Comment by escaped** [comment]
Hey @lifenautjoe, just wanted to check in whether you already had a chance to test this PR. No sweat if you haven't. I might be able to run a proper test against some remote storage over the holiday season.

**Comment by escaped** [comment]
I just tested this implementation using `django-storage` and dropbox as a backend. Worked flawless :)

**Pull request merged**
